version: '3.2'

services:
  db:
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=nextcloud
     - POSTGRES_DB=nextcloud
     - POSTGRES_USER=nextcloud
    #  - POSTGRES_DB_FILE=/run/secrets/postgres_db
    #  - POSTGRES_USER_FILE=/run/secrets/postgres_user
    #  - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
   # secrets:
   #   - postgres_db
   #   - postgres_password
   #   - postgres_user

  app:
    image: nextcloud:stable-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
     # - DB_PORT=5432
     # - POSTGRES_DB_FILE=/run/secrets/postgres_db
     # - POSTGRES_USER_FILE=/run/secrets/postgres_user
     # - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
     # - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
     # - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    depends_on:
      - db
    #secrets:
    #  - nextcloud_admin_password
    #  - nextcloud_admin_user
    #  - postgres_db
    #  - postgres_password
    #  - postgres_user

volumes:
  db:
  nextcloud:

#secrets:
 # nextcloud_admin_password:
 #  file: ./nextcloud_admin_password.txt # put admin password to this file
 # nextcloud_admin_user:
 #   file: ./nextcloud_admin_user.txt # put admin username to this file
 # postgres_db:
 #   file: ./postgres_db.txt # put postgresql db name to this file
 # postgres_password:
 #   file: ./postgres_password.txt # put postgresql password to this file
 # postgres_user:
#    file: ./postgres_user.txt # put postgresql username to this file
